WIP build fails
[kushal@ideapadflex-kushal ~]$
[kushal@ideapadflex-kushal ~]$ script -a ~/log/$(date -u +%FT%H%M%Z).log
Script started, file is /home/kushal/log/2020-03-17T2054UTC.log
[kushal@ideapadflex-kushal ~]$ cd ~/src/ondotnetangularfrontend/;yarn install;ng build > buildfails.txt;git add .;git commit;git pull -r origin master;git push origin master
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.32s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.73s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2.13s
➤ YN0000: Done in 3.37s
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/init.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-0XmSdb/angular-errors.log" for further details.
[master 24d9b1b] WIP build fails
 2 files changed, 23246 insertions(+), 3 deletions(-)
 create mode 100755 .pnp.js
From github.com:ondotnet/angularfrontend
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 205.93 KiB | 737.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:ondotnet/angularfrontend.git
   63b1347..24d9b1b  master -> master
[kushal@ideapadflex-kushal ondotnetangularfrontend]$ cat /tmp/ng-0XmSdb/angular-errors.log
[error] Error: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/init.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:41:41)
    at BuildCommand.initialize (/home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js:134:55)
    at async BuildCommand.validateAndRun (/home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js:62:31)

[kushal@ideapadflex-kushal ondotnetangularfrontend]$ cd ~/src/ondotnetangularfrontend/;yarn install;ng build > buildfails.txt;git add .;git commit;git pull -r origin master;git push origin master
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.37s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.71s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2.12s
➤ YN0000: Done in 3.4s
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/init.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-16BR4U/angular-errors.log" for further details.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
From github.com:ondotnet/angularfrontend
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Everything up-to-date
[kushal@ideapadflex-kushal ondotnetangularfrontend]$ cd ~/src/ondotnetangularfrontend/;yarn install;ng build >> buildfails.txt;git add .;git commit;git pull -r origin master;git push origin master
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.33s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.72s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2.11s
➤ YN0000: Done in 3.38s
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/init.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-6DiZGI/angular-errors.log" for further details.
[master 41479dd] WIP build fails
 1 file changed, 63 insertions(+)
From github.com:ondotnet/angularfrontend
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 3.14 KiB | 3.14 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:ondotnet/angularfrontend.git
   24d9b1b..41479dd  master -> master
[kushal@ideapadflex-kushal ondotnetangularfrontend]$ cd ~/src/ondotnetangularfrontend/;yarn install;ng build >> buildfails.txt;git add .;git commit;git pull -r origin master;git push origin master
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.34s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.72s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2.18s
➤ YN0000: Done in 3.43s
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/architect-command.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/models/command-runner.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/lib/init.js
- /home/kushal/.nvm/versions/node/v13.11.0/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-yuvd1q/angular-errors.log" for further details.
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal ondotnetangularfrontend]$